# Generated by Django 5.1.1 on 2024-09-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('bill_number', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=200)),
                ('status', models.TextField(blank=True, choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Shipped', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_clients', to='clients.clients')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_clients', to='drivers.driver')),
            ],
        ),
    ]
